const themes=[
{name:"Clinical Teal",accent:"#176B67",soft:"#AFD3CF"},{name:"Trust Blue",accent:"#365F86",soft:"#B7C9D9"},{name:"Sage",accent:"#5C765E",soft:"#C2D0C3"},{name:"Plum",accent:"#70546E",soft:"#C7B8C5"},{name:"Coral",accent:"#A65353",soft:"#DAB7B7"},{name:"Indigo",accent:"#4E5F86",soft:"#BDC5D9"},{name:"Forest",accent:"#356650",soft:"#B7CFC3"},{name:"Copper",accent:"#94613E",soft:"#D4BBAA"}];
const fonts=["Manrope","Cormorant Garamond","Playfair Display","Bodoni Moda","DM Serif Display","Prata"];
const root=document.documentElement,reduced=matchMedia("(prefers-reduced-motion: reduce)").matches,systemDark=matchMedia("(prefers-color-scheme: dark)");
let themeIndex=0,fontIndex=0,colourLocked=false,fontLocked=false,selectedMode="light",selectedDoctor="",selectedSpeciality="Cardiology";
const swatches=document.getElementById("themeSwatches"),customColour=document.getElementById("customColour"),customHex=document.getElementById("customHex"),fontSelect=document.getElementById("fontSelect"),colourStatus=document.getElementById("colourStatus"),fontStatus=document.getElementById("fontStatus"),modeStatus=document.getElementById("modeStatus"),lockColour=document.getElementById("lockColour"),lockFont=document.getElementById("lockFont"),lockBoth=document.getElementById("lockBoth");
function hexToRgb(hex){const c=String(hex).replace("#","");if(!/^[0-9a-fA-F]{6}$/.test(c))return null;return[parseInt(c.slice(0,2),16),parseInt(c.slice(2,4),16),parseInt(c.slice(4,6),16)]}
function mix(hex,a=.64){const r=hexToRgb(hex);return r?`#${r.map(v=>Math.round(v+(255-v)*a).toString(16).padStart(2,"0")).join("")}`:"#AFD3CF"}
function applyTheme(t,i=-1){const rgb=hexToRgb(t.accent);if(!rgb)return;root.style.setProperty("--accent",t.accent);root.style.setProperty("--accent-rgb",rgb.join(","));root.style.setProperty("--accent-soft",t.soft||mix(t.accent));customColour.value=t.accent;customHex.value=t.accent.toUpperCase();document.querySelector('meta[name="theme-color"]').content=t.accent;[...swatches.children].forEach((b,n)=>b.classList.toggle("active",n===i))}
function applyFont(f){root.style.setProperty("--display",`"${f}",Georgia,serif`);fontSelect.value=f}
function resolveMode(m){root.dataset.mode=m==="system"?(systemDark.matches?"dark":"light"):m;modeStatus.textContent=m[0].toUpperCase()+m.slice(1);document.querySelectorAll("[data-mode-value]").forEach(b=>b.classList.toggle("active",b.dataset.modeValue===m))}
function updateLocks(){lockColour.classList.toggle("locked",colourLocked);lockFont.classList.toggle("locked",fontLocked);lockBoth.classList.toggle("locked",colourLocked&&fontLocked);lockColour.querySelector("b").textContent=colourLocked?"Locked":"Unlocked";lockFont.querySelector("b").textContent=fontLocked?"Locked":"Unlocked";colourStatus.textContent=colourLocked?"Locked":reduced?"Manual":"Auto · 3 sec";fontStatus.textContent=fontLocked?"Locked":reduced?"Manual":"Auto · 3 sec";lockBoth.textContent=colourLocked&&fontLocked?"Unlock Both":"Lock Both"}
themes.forEach((t,i)=>{const b=document.createElement("button");b.type="button";b.style.setProperty("--swatch",t.accent);b.title=t.name;b.onclick=()=>{themeIndex=i;applyTheme(t,i)};swatches.appendChild(b)});
applyTheme(themes[0],0);applyFont(fonts[0]);resolveMode("light");updateLocks();
if(!reduced){setInterval(()=>{if(!colourLocked){themeIndex=(themeIndex+1)%themes.length;applyTheme(themes[themeIndex],themeIndex)}},3000);setInterval(()=>{if(!fontLocked){fontIndex=(fontIndex+1)%fonts.length;applyFont(fonts[fontIndex])}},3000)}
customColour.oninput=e=>applyTheme({accent:e.target.value.toUpperCase(),soft:mix(e.target.value)});customHex.onchange=e=>{let v=e.target.value.trim();if(!v.startsWith("#"))v="#"+v;hexToRgb(v)?applyTheme({accent:v.toUpperCase(),soft:mix(v)}):e.target.value=getComputedStyle(root).getPropertyValue("--accent").trim()};fontSelect.onchange=e=>{fontIndex=Math.max(0,fonts.indexOf(e.target.value));applyFont(e.target.value)};lockColour.onclick=()=>{colourLocked=!colourLocked;updateLocks()};lockFont.onclick=()=>{fontLocked=!fontLocked;updateLocks()};lockBoth.onclick=()=>{const v=!(colourLocked&&fontLocked);colourLocked=v;fontLocked=v;updateLocks()};document.querySelectorAll("[data-mode-value]").forEach(b=>b.onclick=()=>{selectedMode=b.dataset.modeValue;resolveMode(selectedMode)});systemDark.onchange=()=>selectedMode==="system"&&resolveMode("system");document.getElementById("resetCustomizer").onclick=()=>{themeIndex=fontIndex=0;colourLocked=fontLocked=false;selectedMode="light";applyTheme(themes[0],0);applyFont(fonts[0]);resolveMode("light");updateLocks()};
const customizer=document.querySelector(".customizer"),customizerToggle=document.getElementById("customizerToggle");function setCustomizer(o){customizer.classList.toggle("open",o);customizerToggle.setAttribute("aria-expanded",o)}customizerToggle.onclick=()=>setCustomizer(!customizer.classList.contains("open"));document.getElementById("customizerClose").onclick=()=>setCustomizer(false);
const body=document.body,menuButton=document.getElementById("menuButton"),mainNav=document.getElementById("mainNav");menuButton.onclick=()=>{const o=mainNav.classList.toggle("open");body.classList.toggle("locked",o);menuButton.setAttribute("aria-expanded",o)};mainNav.querySelectorAll("a").forEach(a=>a.onclick=()=>{mainNav.classList.remove("open");body.classList.remove("locked")});
document.querySelectorAll(".reveal").forEach(el=>{if(reduced)el.classList.add("visible");else new IntersectionObserver((entries,obs)=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add("visible");obs.unobserve(e.target)}}),{threshold:.1}).observe(el)});

const deptCards=[...document.querySelectorAll("[data-dept]")];document.querySelectorAll("[data-dept-filter]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-dept-filter]").forEach(x=>x.classList.toggle("active",x===b));deptCards.forEach(c=>c.hidden=b.dataset.deptFilter!=="All"&&c.dataset.dept!==b.dataset.deptFilter&&c.dataset.dept!=="All")});
const doctorCards=[...document.querySelectorAll(".doctor-card")],doctorSearch=document.getElementById("doctorSearch"),doctorSpeciality=document.getElementById("doctorSpeciality"),doctorEmpty=document.getElementById("doctorEmpty");
function filterDoctors(){const q=doctorSearch.value.trim().toLowerCase(),s=doctorSpeciality.value;let count=0;doctorCards.forEach(c=>{const ok=(s==="All"||c.dataset.doctorSpeciality===s)&&(!q||c.dataset.doctorKeywords.includes(q)||c.textContent.toLowerCase().includes(q));c.hidden=!ok;if(ok)count++});doctorEmpty.hidden=count!==0}doctorSearch.oninput=filterDoctors;doctorSpeciality.onchange=filterDoctors;

const today=new Date(),tomorrow=new Date(today);tomorrow.setDate(today.getDate()+1);const minDate=tomorrow.toISOString().split("T")[0];
const appointmentModal=document.getElementById("appointmentModal"),doctorModal=document.getElementById("doctorModal"),reportModal=document.getElementById("reportModal"),simpleModal=document.getElementById("simpleModal");function openD(d){d.showModal();body.classList.add("locked")}function closeD(d){d.close();body.classList.remove("locked")}
const appointmentForm=document.getElementById("appointmentForm");appointmentForm.elements.date.min=minDate;appointmentForm.elements.date.value=minDate;
function openAppointment(){document.getElementById("appointmentSpeciality").value=selectedSpeciality;openD(appointmentModal)}
document.querySelectorAll("[data-open-appointment]").forEach(b=>b.onclick=openAppointment);document.getElementById("appointmentClose").onclick=()=>closeD(appointmentModal);appointmentModal.onclick=e=>e.target===appointmentModal&&closeD(appointmentModal);
document.getElementById("careSearch").onsubmit=e=>{e.preventDefault();const speciality=document.getElementById("careSpeciality").value;if(speciality!=="Any Speciality")selectedSpeciality=speciality;doctorSearch.value=document.getElementById("careQuery").value;doctorSpeciality.value=speciality==="Any Speciality"?"All":speciality;filterDoctors();document.getElementById("doctors").scrollIntoView({behavior:reduced?"auto":"smooth"})};
document.querySelectorAll("[data-department]").forEach(b=>b.onclick=()=>{selectedSpeciality=b.dataset.department;openAppointment()});
document.querySelectorAll("[data-doctor]").forEach(b=>b.onclick=()=>{selectedDoctor=b.dataset.doctor;selectedSpeciality=b.dataset.speciality;document.getElementById("doctorModalTitle").textContent=selectedDoctor;document.getElementById("doctorModalSpeciality").textContent=selectedSpeciality;doctorModal.querySelector(".doctor-modal-media").style.backgroundImage=`url("${b.dataset.image}")`;openD(doctorModal)});document.getElementById("doctorClose").onclick=()=>closeD(doctorModal);doctorModal.onclick=e=>e.target===doctorModal&&closeD(doctorModal);document.getElementById("doctorBook").onclick=()=>{closeD(doctorModal);openAppointment()};

document.querySelectorAll("[data-open-report]").forEach(b=>b.onclick=()=>openD(reportModal));document.getElementById("reportClose").onclick=()=>closeD(reportModal);reportModal.onclick=e=>e.target===reportModal&&closeD(reportModal);document.getElementById("reportForm").onsubmit=e=>{e.preventDefault();open(`https://wa.me/919929562585?text=${encodeURIComponent("Hello Ajay, I am viewing the Velora Health demo. I want a secure medical-report portal feature for a healthcare website.")}`,"_blank","noopener")};

const packages={Essential:{label:"ESSENTIAL · FICTIONAL PACKAGE",title:"Everyday Health Review",description:"A demo preventive package covering common screening categories and a consultation-review placeholder.",price:"₹3,499*"},Advanced:{label:"ADVANCED · FICTIONAL PACKAGE",title:"Comprehensive Health Review",description:"A broader fictional screening set with imaging and specialist-review placeholders.",price:"₹7,999*"},Heart:{label:"HEART FOCUS · FICTIONAL PACKAGE",title:"Cardiac Risk Review",description:"A demo heart-health pathway with consultation, testing and risk-discussion placeholders.",price:"₹5,499*"},Women:{label:"WOMEN’S WELLNESS · FICTIONAL PACKAGE",title:"Women’s Preventive Review",description:"A fictional age-appropriate screening and consultation journey.",price:"₹6,299*"}};
document.querySelectorAll("[data-package]").forEach(b=>b.onclick=()=>{const d=packages[b.dataset.package];document.querySelectorAll("[data-package]").forEach(x=>x.classList.toggle("active",x===b));document.getElementById("packageLabel").textContent=d.label;document.getElementById("packageTitle").textContent=d.title;document.getElementById("packageDescription").textContent=d.description;document.getElementById("packagePrice").textContent=d.price});

function openSimple(eyebrow,title,text,message){document.getElementById("simpleEyebrow").textContent=eyebrow;document.getElementById("simpleTitle").textContent=title;document.getElementById("simpleText").textContent=text;document.getElementById("simpleLink").href=`https://wa.me/919929562585?text=${encodeURIComponent(message)}`;openD(simpleModal)}
document.querySelectorAll("[data-open-check]").forEach(b=>b.onclick=()=>openSimple("HEALTH CHECK · DEMO","Build a clear package journey.","No real health package is booked. Discuss the website feature with AJAYNXT.","Hello Ajay, I am viewing the Velora Health demo. I want a health-check booking feature."));
document.querySelectorAll("[data-diagnostic]").forEach(b=>b.onclick=()=>openSimple("DIAGNOSTICS · DEMO",b.dataset.diagnostic,"A real flow requires verified tests, preparation and secure report handling.",`Hello Ajay, I am viewing the Velora Health demo. I want details about ${b.dataset.diagnostic}.`));
document.querySelectorAll("[data-location-enquiry]").forEach(b=>b.onclick=()=>openSimple("HOSPITAL LOCATION · DEMO",b.dataset.locationEnquiry,"This fictional location demonstrates hospital detail and enquiry pages.",`Hello Ajay, I am viewing the Velora Health demo. I want a hospital-location flow like ${b.dataset.locationEnquiry}.`));
document.querySelectorAll("[data-open-international]").forEach(b=>b.onclick=()=>openSimple("INTERNATIONAL PATIENTS · DEMO","Plan care before travel.","A real desk should use verified estimates, clinical review and travel processes.","Hello Ajay, I am viewing the Velora Health demo. I want an international-patient enquiry flow."));
document.getElementById("simpleClose").onclick=()=>closeD(simpleModal);simpleModal.onclick=e=>e.target===simpleModal&&closeD(simpleModal);

const locationSearch=document.getElementById("locationSearch"),locations=[...document.querySelectorAll("[data-location]")];locationSearch.oninput=()=>{const q=locationSearch.value.trim().toLowerCase();locations.forEach(c=>c.hidden=!!q&&!c.dataset.location.includes(q)&&!c.textContent.toLowerCase().includes(q))};
document.querySelectorAll(".faq-list button").forEach(b=>b.onclick=()=>{const o=b.getAttribute("aria-expanded")==="true";document.querySelectorAll(".faq-list button").forEach(x=>x.setAttribute("aria-expanded","false"));b.setAttribute("aria-expanded",String(!o))});

function setErr(input,msg){input.setAttribute("aria-invalid",String(Boolean(msg)));const s=input.closest("label")?.querySelector(".field-error");if(s)s.textContent=msg;return!msg}
function validate(i){if(i.required&&!i.value.trim())return setErr(i,"This field is required.");if(i.name==="phone"&&!/^[0-9+\s()-]{8,18}$/.test(i.value.trim()))return setErr(i,"Enter a valid phone number.");return setErr(i,"")}
function validForm(f){const fields=[...f.querySelectorAll("[required]")],ok=fields.map(validate).every(Boolean);if(!ok)fields.find(x=>x.getAttribute("aria-invalid")==="true")?.focus();return ok}
appointmentForm.onsubmit=e=>{e.preventDefault();if(!validForm(appointmentForm))return;const d=new FormData(appointmentForm),msg=["Hello Ajay, I am viewing the Velora Health demo.","","Demo appointment enquiry:",`Patient Name: ${d.get("name")}`,`Phone: ${d.get("phone")}`,`Speciality: ${d.get("speciality")}`,`Location: ${d.get("location")}`,`Date: ${d.get("date")}`,`Mode: ${d.get("mode")}`,`Reason: ${d.get("reason")||""}`,"","This is a website enquiry, not a medical appointment."].join("\n");open(`https://wa.me/919929562585?text=${encodeURIComponent(msg)}`,"_blank","noopener")};
const priceForm=document.getElementById("priceForm");priceForm.onsubmit=e=>{e.preventDefault();if(!validForm(priceForm))return;const d=new FormData(priceForm),msg=["Hello Ajay, I want a healthcare website price.","",`Name: ${d.get("name")}`,`Phone: ${d.get("phone")}`,`Hospital / Clinic: ${d.get("business")||""}`,`Website Type: ${d.get("type")}`,`Project Details: ${d.get("message")||""}`,"","Reference: Velora Health Demo"].join("\n");open(`https://wa.me/919929562585?text=${encodeURIComponent(msg)}`,"_blank","noopener")};
